language: node_js
node_js:
  - "0.8"
  - "0.10"
  - "0.11"
  - iojs
  - iojs-v1.0.2

matrix:
  allow_failures:
    - node_js: "0.8"
    - node_js: "0.11"
    - node_js: iojs
    - node_js: iojs-v1.0.2
